// Retained, non-rendered Welsh copy from the Phase 3A bilingual prototype.
// This is reference material for a future selective-Welsh UX pass, not an
// active language pack or language-toggle implementation.
export const RETAINED_WELSH_RUNNER_COPY = Object.freeze({
  skipToMain: "Neidio i'r prif gynnwys",
  backToEntryInformation: "Yn ôl i wybodaeth gofrestru",
  registrationTitle: "Cofrestru Ras Fell y Blorenge",
  privateAccess: "Mynediad preifat",
  unavailableLink: "Dydy'r ddolen hon ddim ar gael bellach.",
  organiserHelp: "Gofynnwch i drefnydd y ras am help.",
  registrationStatus: "Statws cofrestru",
  entriesNotOpen: "Dydy cofrestru ar gyfer 2026 ddim ar agor eto",
  runnerDetails: "Eich manylion",
  firstName: "Enw cyntaf",
  lastName: "Cyfenw",
  email: "Cyfeiriad e-bost",
  phone: "Rhif ffôn",
  addressLine1: "Llinell cyfeiriad 1",
  addressLine2: "Llinell cyfeiriad 2",
  city: "Dinas",
  postcode: "Cod post",
  dateOfBirth: "Dyddiad geni",
  raceCategory: "Categori ras",
  female: "Benyw",
  maleOpen: "Gwryw / Agored",
  club: "Clwb",
  wfraMember: "Ydych chi'n aelod o WFRA?",
  wfraMembershipNumber: "Rhif aelodaeth WFRA",
  emergencyContactName: "Enw cyswllt mewn argyfwng",
  emergencyContactPhone: "Rhif ffôn cyswllt mewn argyfwng",
  declaration: "Datganiad cystadleuydd WFRA",
  signingRole: "Pwy sy'n llofnodi?",
  competitor: "Cystadleuydd",
  parentOrGuardian: "Rhiant / Gwarcheidwad Cyfreithiol",
  continue: "Parhau",
  back: "Yn ôl",
  reviewAndSubmit: "Adolygu a chyflwyno",
  confirmation: "Cofrestriad prawf wedi'i gadarnhau"
});
